spring.application.name=TSIPPOLibrary

server.port=8080

jwt-secret=fdLwz0v0J3UQDrb+DJl2+618BLj24xPq+ZZkU95uUsQ=
jwt-expiration=3600000
jwt-refresh-expiration=604800000

spring.datasource.url=spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:library}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=${POSTGRES_PASWORD:postgres}
spring.datasource.username=${POSTGRES_USER:postgres}

springdoc.swagger-ui.url=localhost://8090